### ISSUE TITLE
add method to fetch meta data

### ISSUE THREAD

**Issue by mac-s-g** [michaelferrell/cabinet.js#20]
`Cabinet.get` returns the value stored in localStorage.

I can see that Cabinet stores `dateCreated` and `type` properties with all stored values.

can you add a method that allows me to fetch the additional data for a stored value?

I'm thinking of something like this:
```javascript
Cabinet.get(my_value_key) // return value associated with my_value_key
Cabinet.meta(my_value_key) // return meta data associated with stored value 
```

other possible names:
`Cabinet.detail(...)`, `Cabinet.describe(...)`, `Cabinet.getDetail(...)`

**Comment by michaelferrell** [comment]
done
